### ISSUE TITLE
Use `--lzma` option with upx

### ISSUE THREAD

**Issue by simnalamburt** [kinoru/wild#2]
Except 16-bit architecture, using `--lzma` gives you advantages in both speed and size. Let's use this!

(Does ghci even support 16-bit architecture?)

![](https://cloud.githubusercontent.com/assets/4435445/14219063/065a6738-f893-11e5-818c-8595f60fa1cc.png)

**Comment by xtendo-org** [comment]
Thanks for the report.

Done in 090e14f3ea3503e26beee825a1fa6bbfd515f362.
